# Generated by Django 3.2.5 on 2021-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tags', models.CharField(max_length=255, verbose_name='Tags')),
            ],
        ),
    ]
